### ISSUE TITLE
Add Framework specific presets and Tests

### ISSUE THREAD

**Issue by ayimdomnic** [osenco/mpesats#2]
### Aim

Hey, Great work on the library.

I am thinking of adding framework specific presets for this so users of `nestjs`, `adonis`, `loopback 4` can just inject this to their entry points and let the framework do all the work

if this is a direction you want this to go I'll be more than happy to make the PR this long weekend

Also, it would be cool to have an issue and PR templates for folks like me who can't type for sh*t

Regards

**Comment by maukoese** [comment]
Hi, sure thing.

I think supporting that out of the box would be amazing.

**Comment by ayimdomnic** [comment]
@maukoese Then I propose this structure,
we make this a lerna monorepo and separate the framework specific presets as packages as well, that way we can achieve backward compatibility and also not force users of the core package to install the other distributions of this

```
packages/
   @osenco/
       mpesa-core/
       mpesa-nestjs/
       mpesa-lb/
       mpesa-adonis/
```
what do you think?
